#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x18 (0x188 - 0x170)
// BlueprintGeneratedClass BP_StructureEstateComponent.BP_StructureEstateComponent_C
class UBP_StructureEstateComponent_C : public UStructureEstateComponent
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x170(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class URealmRespitesComponent*               RealmRespitesComponent;                            // 0x178(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ANWXOwnedPlayerStart*                  RespitePoint;                                      // 0x180(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UBP_StructureEstateComponent_C* GetDefaultObj();

	void OnOwnerMoved(class UObject* MovedEntity, const struct FTransform& Temp_struct_Variable, class AActor* CallFunc_GetOwner_ReturnValue, TScriptInterface<class IPortalActorInterface> K2Node_DynamicCast_AsPortal_Actor_Interface, bool K2Node_DynamicCast_bSuccess, class ANWXPlayerController* CallFunc_GetOwningNWXPlayerController_AsNWXPlayer_Controller, const struct FTransform& CallFunc_GetPlayerSpawnTransform_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void RemoveRespitePoint(class ANWXPlayerController* NWXPlayerController, bool CallFunc_RemoveRespitePoint_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, TScriptInterface<class IBPI_PlayerAccountInfo_C> K2Node_DynamicCast_AsBPI_Player_Account_Info, bool K2Node_DynamicCast_bSuccess, class AActor* CallFunc_GetOwner_ReturnValue, const class FString& CallFunc_GetPersistentUniqueIdFromPawn_PersistentId, TScriptInterface<class IPlaceableEntityInterface> K2Node_DynamicCast_AsPlaceable_Entity_Interface, bool K2Node_DynamicCast_bSuccess_1);
	void CreateRespitePoint(class ANWXPlayerController* NWXPlayerController, class APawn* CallFunc_K2_GetPawn_ReturnValue, TScriptInterface<class IBPI_PlayerAccountInfo_C> K2Node_DynamicCast_AsBPI_Player_Account_Info, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, const class FString& CallFunc_GetPersistentUniqueIdFromPawn_PersistentId, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class AActor* CallFunc_GetOwner_ReturnValue, TScriptInterface<class IPlaceableEntityInterface> K2Node_DynamicCast_AsPlaceable_Entity_Interface, bool K2Node_DynamicCast_bSuccess_1, enum class EFeatureFlagStatus CallFunc_FeatureFlagBranch_Result, bool K2Node_SwitchEnum_CmpSuccess, const struct FTransform& Temp_struct_Variable, enum class EFeatureFlagStatus CallFunc_FeatureFlagBranch_Result_1, bool K2Node_SwitchEnum_CmpSuccess_1, class ANWXOwnedPlayerStart* CallFunc_CreateRespitePoint_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class AActor* CallFunc_GetOwner_ReturnValue_1, class USceneComponent* CallFunc_K2_GetRootComponent_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_2, bool CallFunc_K2_AttachToComponent_ReturnValue, TScriptInterface<class IPortalActorInterface> K2Node_DynamicCast_AsPortal_Actor_Interface, bool K2Node_DynamicCast_bSuccess_2, const struct FTransform& CallFunc_GetPlayerSpawnTransform_ReturnValue);
	void OnOwningStructureDestroyed(class UObject* Structure, class AActor* Instigator, class ANWXPlayerController* LPlayerController, class UStructureEstateComponent* EstateComponent, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_IsPlayerInRespiteRealm_ReturnValue, bool CallFunc_RemoveRespitePoint_ReturnValue, class AActor* CallFunc_CreateRespiteAtStartSpot_ReturnValue, class ANWXPlayerController* CallFunc_GetOwningNWXPlayerController_AsNWXPlayer_Controller, bool CallFunc_SetPlayerHasRespiteStructure_ReturnValue, bool CallFunc_IsRespitePoint_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void GetOwningNWXPlayerController(class ANWXPlayerController** AsNWXPlayer_Controller, class AActor* CallFunc_GetOwner_ReturnValue, const class FString& CallFunc_GetFunctionName_ReturnValue, bool CallFunc_HasOwningPlayer_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, const class FString& CallFunc_GetFunctionName_ReturnValue_1, class AActor* CallFunc_GetOwner_ReturnValue_2, class AActor* CallFunc_GetOwner_ReturnValue_3, class AController* CallFunc_GetOwningPlayerController_OutPlayerController, bool CallFunc_GetOwningPlayerController_ReturnValue, class ANWXPlayerController* K2Node_DynamicCast_AsNWXPlayer_Controller, bool K2Node_DynamicCast_bSuccess);
	void ManageRespitePointSpawning(bool IsRespitePoint, class ANWXPlayerController* NWXPlayerController, class AController* PlayerController, class ANWXPlayerController* CallFunc_GetOwningNWXPlayerController_AsNWXPlayer_Controller, bool CallFunc_IsValid_ReturnValue);
	void SetRespitePoint(bool bCurrentRespitePoint, int32 Temp_int_Array_Index_Variable, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, class AActor* CallFunc_GetOwner_ReturnValue_2, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_3, const class FString& CallFunc_GetOwningPlayerID_OutPlayerId, bool CallFunc_GetOwningPlayerID_ReturnValue, TArray<class ANWXStructure*>& CallFunc_GetAllEstates_OutEstates, class ANWXStructure* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, TScriptInterface<class IStructureEstateInterface> K2Node_DynamicCast_AsStructure_Estate_Interface, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Less_IntInt_ReturnValue, class UStructureEstateComponent* CallFunc_GetStructureEstateComponentForModify_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue);
	void OnOwningStructureStateChanged(class ANWXPlayerController* LPlayerController, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_DoesPlayerHaveRespiteStructure_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_CanPlayerSetRespiteInRealm_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue, const class FString& CallFunc_GetOwningPlayerID_OutPlayerId, bool CallFunc_GetOwningPlayerID_ReturnValue, enum class EFeatureFlagStatus CallFunc_FeatureFlagBranch_Result, class ANWXPlayerController* CallFunc_GetOwningNWXPlayerController_AsNWXPlayer_Controller, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_IsValid_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_2, TScriptInterface<class IStructureStateInterface> K2Node_DynamicCast_AsStructure_State_Interface, bool K2Node_DynamicCast_bSuccess, bool CallFunc_GetIsStructureComplete_ReturnValue);
	void UpdateOwningPlayerEstateScore(class UAbilitySystemComponent* LPlayerAbilitySystemComponent, bool CallFunc_IsRespitePoint_ReturnValue, bool CallFunc_IsServer_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, class APlayerState* CallFunc_GetOwningPlayerState_OutPlayerState, bool CallFunc_GetOwningPlayerState_ReturnValue, bool CallFunc_IsValid_ReturnValue, class APawn* CallFunc_GetPawn_ReturnValue, class UAbilitySystemComponent* CallFunc_GetAbilitySystemComponent_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, const struct FGameplayEffectSpecHandle& CallFunc_MakeOutgoingSpec_ReturnValue, const struct FGameplayEffectSpecHandle& CallFunc_AssignTagSetByCallerMagnitude_ReturnValue, const struct FActiveGameplayEffectHandle& CallFunc_BP_ApplyGameplayEffectSpecToSelf_ReturnValue);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_StructureEstateComponent(int32 EntryPoint, class ANWXGameStateBase* CallFunc_GetNWXGameStateBase_ReturnValue, class URealmRespitesComponent* CallFunc_GetRealmRespitesComponent_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class ANWXStructure* K2Node_DynamicCast_AsNWXStructure, bool K2Node_DynamicCast_bSuccess, class AActor* CallFunc_GetOwner_ReturnValue_1, TScriptInterface<class IStructureEventInterface> K2Node_DynamicCast_AsStructure_Event_Interface, bool K2Node_DynamicCast_bSuccess_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class UStructureEventsObject* CallFunc_GetStructureEventsObject_ReturnValue);
};

}


